HOT6/BikeShop.Website/Controllers/ShopController.cs
using BikeShop.Website.Models;
using BikeShop.Website.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BikeShop.Website.Controllers
{
    public class ShopController : Controller
    {
        private BikeShopDatabase db = new BikeShopDatabase();

        // GET: Category
        public ActionResult Index(
            string search,
            byte? categoryId,
            int? minPrice,
            int? maxPrice,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            var products =
                from p in db.Products
                join c in db.Categories on p.CategoryId equals c.CategoryId
                orderby p.ProductId, c.CategoryId
                select new BikeShopInfo
                {
                    ProductId = p.ProductId,
                    ProductName = p.ProductName,
                    RetailPrice = p.RetailPrice,
                    Quantity = p.QuantityOnHand,
                    CategoryId = c.CategoryId,
                    CategoryName = c.CategoryName
                };

            if (!string.IsNullOrEmpty(search))
            {
                products = products.Where(x => x.ProductName.Contains(search) || x.CategoryName.Contains(search));
            }
            if (categoryId != null)
            {
                products = products.Where(x => x.CategoryId == categoryId);
            }
            if (minPrice != null)
            {
                products = products.Where(x => x.RetailPrice >= minPrice);
            }
            if (maxPrice != null)
            {
                products = products.Where(x => x.RetailPrice <= maxPrice);
            }

            switch (sortBy)
            {
                default:
                    products = products.OrderBy(e => e.ProductId);
                    break;
                case "Category #":
                    products = products.OrderBy(e => e.CategoryId);
                    break;
                case "Product #":
                    products = products.OrderBy(e => e.ProductId);
                    break;
                case "Price":
                    products = products.OrderBy(e => e.RetailPrice);
                    break;
                case "Product Name":
                    products = products.OrderBy(e => e.ProductName);
                    break;
            }



            var model = new BikeShopSearchResults
            {
                Search = search,
                CategoryId = categoryId,
                MinPrice = minPrice,
                MaxPrice = maxPrice,
                SortBy = sortBy,
                Categories = db.Categories.OrderBy(c => c.CategoryName).ToList(),
                Results = products.ToPagedList(page ?? 1, itemsPerPage ?? 5)
            };

            ViewBag.Search = search;
            ViewBag.CategoryId = categoryId;
            ViewBag.MinPrice = minPrice;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.SortBy = sortBy;
            ViewBag.Genres = db.Categories.OrderBy(c => c.CategoryName).ToList();

            return View("Index", model);
        }
    }
}

HOT6/BikeShop.Website/Views/Shop/Index.cshtml
@model BikeShop.Website.ViewModels.BikeShopSearchResults
@using PagedList.Mvc;
@{
    ViewBag.Title = "Bike Shop";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Shop", FormMethod.Get))
{
    var categories = new SelectList(Model.Categories, "CategoryId", "CategoryName");

    var sortByArray = new SelectListItem[]
    {
        new SelectListItem { Value = "CategoryId", Text = "Category #" },
        new SelectListItem { Value = "ProductId", Text = "Product #" },
        new SelectListItem { Value = "RetailPrice", Text = "Price" },
        new SelectListItem { Value = "ProductName", Text = "Name" }
    };
    var sortByList = new SelectList(sortByArray, "Value", "Text");

    <div class="mb-3">
        @Html.DropDownListFor(m => m.Categories, categories, "(All)")
        @Html.EditorFor(m => m.Search, new { htmlAttributes = new { placeholder = "Search" } })
        @Html.EditorFor(m => m.MinPrice, new { htmlAttributes = new { placeholder = "Min" } })
        @Html.EditorFor(m => m.MaxPrice, new { htmlAttributes = new { placeholder = "Max" } })
        @Html.DropDownListFor(m => m.SortBy, sortByList)
        <input class="btn btn-primary" type="submit" value="Apply" />
    </div>
}

<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Name
        </th>
        <th>
            Price
        </th>
        <th>
            Quantity
        </th>
        <th>
            Category
        </th>
    </tr>

    @foreach (var item in Model.Results)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RetailPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
        </tr>
    }
</table>
<br />
<div>
    @Html.PagedListPager(
        Model.Results,
        page => Url.Action("Index", new
        {
            Search = Model.Search,
            CategoryId = Model.CategoryId,
            MinPrice = Model.MinPrice,
            MaxPrice = Model.MaxPrice,
            SortBy = Model.SortBy,
            Page = page,
            ItemsPerPage = Model.Results.PageSize,
        }),
        new PagedListRenderOptions
        {
            Display = PagedListDisplayMode.IfNeeded,
            DisplayPageCountAndCurrentLocation = true,
            DisplayEllipsesWhenNotShowingAllPageNumbers = true,
            MaximumPageNumbersToDisplay = 5,
            PageCountAndCurrentLocationFormat = "Page {0} of {1}"
        }
    )
</div>

@section scripts
{
    <script>
 $(".pagination > li").addClass("page-item");
 $(".pagination > li > a").addClass("page-link");
    </script>
}