WK5/Labs/Controllers/MpgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Labs.Controllers
{
    public class MpgController : Controller
    {
        // GET: Mpg
        public ActionResult Index(float? milesDriven, float? gallonsUsed, float? pricePerGallon)
        {
            ViewBag.milesDriven = milesDriven;
            ViewBag.gallonsUsed = gallonsUsed;
            ViewBag.pricePerGallon = pricePerGallon;

            ViewBag.Mpg = milesDriven / gallonsUsed;
            ViewBag.tripCost = (gallonsUsed * pricePerGallon);
            ViewBag.costPerMile = (ViewBag.tripCost / milesDriven);

            return View();
        }
    }
}

WK5/Labs/Views/Mpg/Index.cshtml
@{
    ViewBag.Title = "Miles Per Gallon";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Index", "Mpg", FormMethod.Post))
{
    <div>
        @Html.Label("milesDriven", "Miles Driven:")
        @Html.TextBox("milesDriven", (object)ViewBag.milesDriven)
        <br />
        @Html.Label("gallonsUsed", "Gallons Used:")
        @Html.TextBox("gallonsUsed", (object)ViewBag.gallonsUsed)
        <br />
        @Html.Label("pricePerGallon", "Price Per Gallon:")
        @Html.TextBox("pricePerGallon", (object)ViewBag.pricePerGallon)
        <input type="submit" value="Calculate" />
    </div>
}

@if (@ViewBag.mpg != null)
{
    <p>Your average MPG is @ViewBag.Mpg</p>
    <p>Your trip cost is @ViewBag.tripCost</p>
    <p>Your cost per mile is @ViewBag.costPerMile</p>
}