employees/EmployeeWebsite/Models/Extensions/employee.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeWebsite.Models
{
    [MetadataType(typeof(employee_metadata))]
    public partial class employee
    {
    }
    
    public partial class employee_metadata
    {
        [Display(Name = "Employee #")]
        public int emp_no { get; set; }
        [Required(ErrorMessage = "Birth date is required.")]
        [Display(Name = "Birth Date")]
        public DateTime birth_date { get; set; }
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First name is required.")]
        public string first_name { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last name is required.")]
        public string last_name { get; set; }
        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Gender is required.")]
        [MinLength(1)]
        public string gender { get; set; }
        [Display(Name = "Hire Date")]
        [Required(ErrorMessage = "Hire date is required.")]
        public DateTime hire_date { get; set; }
        public string emp_image { get; set; }

        public string dept_no { get; set; }

        //[NotMapped]
        //public string full_name
        //{
        //    get { return first_name + " " + last_name; }
        //}
    }
}

employees/EmployeeWebsite/Models/employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.dept_emp = new HashSet<dept_emp>();
            this.dept_manager = new HashSet<dept_manager>();
            this.salaries = new HashSet<salary>();
            this.titles = new HashSet<title>();
        }
    
        public int emp_no { get; set; }
        public System.DateTime birth_date { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public System.DateTime hire_date { get; set; }
        public string dept_no { get; set; }
        public string emp_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dept_emp> dept_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dept_manager> dept_manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salary> salaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<title> titles { get; set; }
    }
}

employees/EmployeeWebsite/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using EmployeeWebsite.Models;
using EmployeeWebsite.ViewModels;
using PagedList;

namespace EmployeeWebsite.Controllers
{
    public class EmployeeController : Controller
    {
        private EmployeeDatabase db = new EmployeeDatabase();

        // GET: ScaffoldEmployee
        public ActionResult Index(
            string search,
            string dept_no,
            int? minYear,
            int? maxYear,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            var emps =
                from e in db.employees
                join d in db.departments on e.dept_no equals d.dept_no
                //where e.last_name == "Lenart" // Testing
                orderby e.emp_no, e.dept_no
                select new EmployeeInfo
                {
                    emp_no = e.emp_no,
                    last_name = e.last_name,
                    first_name = e.first_name,
                    hire_date = e.hire_date,
                    dept_no = e.dept_no,
                    dept_name = d.dept_name,
                    emp_image = e.emp_image
                };
            // Search
            if (!string.IsNullOrEmpty(search))
            {
                emps = emps.Where(x => x.dept_name == search || x.last_name == search || x.first_name == search);
            }
            if (dept_no != null)
            {
                emps = emps.Where(x => x.dept_no == dept_no);
            }

            // Sorting
            switch (sortBy)
            {
                default:
                    emps = emps.OrderBy(e => e.emp_no);
                    break;
                case "Employee #":
                    emps = emps.OrderBy(e => e.emp_no);
                    break;
                case "Last Name":
                    emps = emps.OrderBy(e => e.last_name);
                    break;
                case "First Name":
                    emps = emps.OrderBy(e => e.first_name);
                    break;
                case "Hire Date":
                    emps = emps.OrderBy(e => e.hire_date);
                    break;
                case "Department":
                    emps = emps.OrderBy(e => e.dept_name);
                    break;
            }

            var model = new EmployeeSearchResults
            {
                Search = search,
                Dept_no = dept_no,
                MinYear = minYear,
                MaxYear = maxYear,
                SortBy = sortBy,
                Departments = db.departments.OrderBy(d => d.dept_name).ToList(),
                Results = emps.ToPagedList(page ?? 1, itemsPerPage ?? 5)
            };

            ViewBag.Search = search;

            return View("Index", model);
        }

        // GET: ScaffoldEmployee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: ScaffoldEmployee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ScaffoldEmployee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "emp_no,birth_date,first_name,last_name,gender,hire_date,dept_no,emp_image")]
        employee employee,
        HttpPostedFileBase imageUpload)
        {
            if (imageUpload != null && ValidateImage(imageUpload))
            {
                SaveEmpImage(imageUpload, employee);
            }

            if (ModelState.IsValid)
            {
                db.employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: ScaffoldEmployee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: ScaffoldEmployee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "emp_no,birth_date,first_name,last_name,gender,hire_date,dept_no,emp_image")]
        employee employee,
        HttpPostedFileBase imageUpload)
        {
            if (imageUpload != null && ValidateImage(imageUpload))
            {
                SaveEmpImage(imageUpload, employee);
            }

            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        public bool ValidateImage(HttpPostedFileBase file)
        {
            if (file == null)
            {
                ModelState.AddModelError("myFile", "Please select a file");
                return false;
            }
            else if (file.ContentLength <= 0)
            {
                ModelState.AddModelError("myFile", "File invalid");
                return false;
            }
            else if (file.ContentLength > Constants.MAX_UPLOAD_SIZE)
            {
                ModelState.AddModelError("myFile", "File too big");
                return false;
            }

            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            if (!Constants.FILE_EXTENSIONS.Contains(fileExtension))
            {
                ModelState.AddModelError("myFile", $"{fileExtension} is not a valid file extension please use another");
                return false;
            }
            return true;
        }

        public void SaveEmpImage(HttpPostedFileBase image, employee employee)
        {
            string fileName = image.FileName;

            WebImage img = new WebImage(image.InputStream);
            if (img.Width > 300 || img.Height > 450)
            {
                img.Resize(300, 450);
            }
            img.Save(Constants.EMP_IMAGES + fileName);

            // Image Resize
            img.Resize(100, 100);
            img.Save(Constants.EMP_IMAGES + Constants.THUMBNAILS + fileName);

            // Save Image
            employee.emp_image = fileName;
        }

        // GET: ScaffoldEmployee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            employee employee = db.employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: ScaffoldEmployee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            employee employee = db.employees.Find(id);
            db.employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

employees/EmployeeWebsite/Views/Employee/Create.cshtml
@model EmployeeWebsite.Models.employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Employee", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.emp_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_image, new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" name="imageUpload" class="form-control"/>
                @Html.ValidationMessageFor(model => model.emp_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birth_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birth_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birth_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hire_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hire_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hire_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dept_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dept_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dept_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

employees/EmployeeWebsite/Views/Employee/Delete.cshtml
@model EmployeeWebsite.Models.employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.birth_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birth_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hire_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hire_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dept_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dept_no)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

employees/EmployeeWebsite/Views/Employee/Details.cshtml
@model EmployeeWebsite.Models.employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.birth_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birth_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hire_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hire_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dept_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dept_no)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.emp_no }) |
    @Html.ActionLink("Back to List", "Index")
</p>

employees/EmployeeWebsite/Views/Employee/Edit.cshtml
@model EmployeeWebsite.Models.employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Employee", FormMethod.Post, new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.emp_no)

        <div class="form-group">
            @Html.LabelFor(model => model.emp_image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_image, new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" name="imageUpload" class="form-control"/>
                @Html.ValidationMessageFor(model => model.emp_image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birth_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birth_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birth_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hire_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hire_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hire_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dept_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dept_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dept_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

employees/EmployeeWebsite/Views/Employee/Index.cshtml
@model EmployeeWebsite.ViewModels.EmployeeSearchResults
@using PagedList.Mvc;
@using EmployeeWebsite.ViewModels;

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("Index", "Employee", FormMethod.Get))
{
    var departments = new SelectList(Model.Departments, "dept_no", "dept_name");

    var sortByArray = new SelectListItem[]
    {
        new SelectListItem { Value = "emp_no", Text = "Employee #" },
        new SelectListItem { Value = "last_name", Text = "Last Name" },
        new SelectListItem { Value = "first_name", Text = "First Name" },
        new SelectListItem { Value = "hire_date", Text = "Hire Date" },
        new SelectListItem { Value = "dept_name", Text = "Department" }
    };
    var sortByList = new SelectList(sortByArray, "Value", "Text");

    <div class="mb-3">
        @Html.DropDownListFor(m => m.Dept_no, departments, "(All)")
        @Html.EditorFor(m => m.MinYear, new { htmlAttributes = new { placeholder = "Min" } })
        @Html.EditorFor(m => m.MaxYear, new { htmlAttributes = new { placeholder = "Max" } })
        @Html.DropDownListFor(m => m.SortBy, sortByList)
        <input class="btn btn-primary" type="submit" value="Apply" />
    </div>
}
<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            Portrait
        </th>
        <th>
            Last Name
        </th>
        <th>
            First Name
        </th>
        <th>
            Hire Date
        </th>
        <th>
            Department
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Results) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.emp_no)
        </td>
        <td>
            @if (!string.IsNullOrWhiteSpace(item.emp_image))
            {
                string url = Url.Content(
                    Constants.EMP_IMAGES +
                    Constants.THUMBNAILS + item.emp_image
                    );
                <img src="@url" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.last_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.first_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.hire_date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dept_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dept_no)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.emp_no }) |
            @Html.ActionLink("Details", "Details", new { id = item.emp_no }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.emp_no })
        </td>
    </tr>
}
</table>
<p>
    @Html.ActionLink("Hire Employee", "Create")
</p>